"""initial schema

Revision ID: 8ee63a38875c
Revises:
Create Date: 2025-11-13 19:35:18.840751

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ee63a38875c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("index_notifi_user"), table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("index_analytic_usertype"), table_name="analyticsevent")
    op.drop_table("analyticsevent")
    op.drop_table("badge")
    op.drop_table("teacher")
    op.drop_table("role")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_table("enrollment")
    op.drop_index(op.f("index_question_set"), table_name="question")
    op.drop_table("question")
    op.drop_table("versionhistory")
    op.drop_index(op.f("index_class_teacher"), table_name="class")
    op.drop_table("class")
    op.drop_index(op.f("index_user_role"), table_name="User")
    op.drop_table("User")
    op.drop_index(op.f("index_attempt_userset"), table_name="attempt")
    op.drop_table("attempt")
    op.drop_table("leaderboardentry")
    op.drop_index(op.f("index_studyset_creator"), table_name="studyset")
    op.drop_table("studyset")
    op.drop_index(op.f("index_ai_userdifficulty"), table_name="aisuggestion")
    op.drop_table("aisuggestion")
    op.drop_index(op.f("ix_revoked_tokens_jti"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "revoked_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("revoked_tokens_pkey")),
    )
    op.create_index(
        op.f("ix_revoked_tokens_jti"), "revoked_tokens", ["jti"], unique=True
    )
    op.create_table(
        "aisuggestion",
        sa.Column("suggestion_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "recommended_set_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "difficulty_level",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["recommended_set_id"],
            ["studyset.set_id"],
            name=op.f("aisuggestion_recommended_set_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.user_id"],
            name=op.f("aisuggestion_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("suggestion_id", name=op.f("aisuggestion_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "recommended_set_id",
            name=op.f("aisuggestion_user_id_recommended_set_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("index_ai_userdifficulty"),
        "aisuggestion",
        ["user_id", "difficulty_level"],
        unique=False,
    )
    op.create_table(
        "studyset",
        sa.Column(
            "set_id",
            sa.INTEGER(),
            server_default=sa.text("nextval('studyset_set_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "subject", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.CheckConstraint(
            "char_length(subject::text) > 0", name="studyset_subject_check"
        ),
        sa.CheckConstraint("char_length(title::text) > 1", name="studyset_title_check"),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["User.user_id"],
            name="studyset_creator_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("set_id", name="studyset_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("index_studyset_creator"), "studyset", ["creator_id"], unique=False
    )
    op.create_table(
        "leaderboardentry",
        sa.Column("entry_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("class_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.CheckConstraint(
            "score >= 0::double precision AND score <= 100::double precision",
            name=op.f("leaderboardentry_score_check"),
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.class_id"],
            name=op.f("leaderboardentry_class_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.user_id"],
            name=op.f("leaderboardentry_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("leaderboardentry_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "class_id",
            name=op.f("leaderboardentry_user_id_class_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "attempt",
        sa.Column("attempt_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("set_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "score >= 0::double precision AND score <= 100::double precision",
            name=op.f("attempt_score_check"),
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["studyset.set_id"],
            name=op.f("attempt_set_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.user_id"],
            name=op.f("attempt_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("attempt_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "set_id",
            "timestamp",
            name=op.f("attempt_user_id_set_id_timestamp_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("index_attempt_userset"), "attempt", ["user_id", "set_id"], unique=False
    )
    op.create_table(
        "User",
        sa.Column(
            "user_id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"User_user_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column(
            "password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.CheckConstraint(
            "POSITION(('@'::text) IN (email)) > 1", name="User_email_check"
        ),
        sa.CheckConstraint("char_length(name::text) >= 2", name="User_name_check"),
        sa.CheckConstraint(
            "char_length(password_hash::text) >= 10", name="User_password_hash_check"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name="User_role_id_fkey"),
        sa.PrimaryKeyConstraint("user_id", name="User_pkey"),
        sa.UniqueConstraint(
            "email",
            name="User_email_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("index_user_role"), "User", ["role_id"], unique=False)
    op.create_table(
        "class",
        sa.Column(
            "class_id",
            sa.INTEGER(),
            server_default=sa.text("nextval('class_class_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "class_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.CheckConstraint(
            "char_length(class_name::text) > 0", name="class_class_name_check"
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teacher.teacher_id"],
            name="class_teacher_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("class_id", name="class_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("index_class_teacher"), "class", ["teacher_id"], unique=False)
    op.create_table(
        "versionhistory",
        sa.Column("version_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("set_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("editor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("diff", sa.TEXT(), autoincrement=False, nullable=False),
        sa.CheckConstraint("diff <> ''::text", name=op.f("versionhistory_diff_check")),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["User.user_id"],
            name=op.f("versionhistory_editor_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["studyset.set_id"],
            name=op.f("versionhistory_set_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("version_id", name=op.f("versionhistory_pkey")),
    )
    op.create_table(
        "question",
        sa.Column("question_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("set_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("correct_answer", sa.TEXT(), autoincrement=False, nullable=False),
        sa.CheckConstraint("content <> ''::text", name=op.f("question_content_check")),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["studyset.set_id"],
            name=op.f("question_set_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("question_id", name=op.f("question_pkey")),
    )
    op.create_index(op.f("index_question_set"), "question", ["set_id"], unique=False)
    op.create_table(
        "enrollment",
        sa.Column("enrollment_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("class_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.class_id"],
            name=op.f("enrollment_class_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.user_id"],
            name=op.f("enrollment_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("enrollment_id", name=op.f("enrollment_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "class_id",
            name=op.f("enrollment_user_id_class_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "roles",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('roles_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="roles_pkey"),
        sa.UniqueConstraint(
            "name",
            name="roles_name_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "role",
        sa.Column("role_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "role_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.CheckConstraint(
            "role_name::text <> ''::text", name=op.f("role_role_name_check")
        ),
        sa.PrimaryKeyConstraint("role_id", name=op.f("role_pkey")),
        sa.UniqueConstraint(
            "role_name",
            name=op.f("role_role_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "teacher",
        sa.Column("teacher_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["User.user_id"],
            name=op.f("teacher_teacher_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("teacher_id", name=op.f("teacher_pkey")),
    )
    op.create_table(
        "badge",
        sa.Column("badge_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("criteria", sa.TEXT(), autoincrement=False, nullable=False),
        sa.CheckConstraint("criteria <> ''::text", name=op.f("badge_criteria_check")),
        sa.CheckConstraint(
            "char_length(name::text) > 0", name=op.f("badge_name_check")
        ),
        sa.PrimaryKeyConstraint("badge_id", name=op.f("badge_pkey")),
    )
    op.create_table(
        "analyticsevent",
        sa.Column("event_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "event_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("metadata", sa.TEXT(), autoincrement=False, nullable=True),
        sa.CheckConstraint(
            "char_length(event_type::text) > 0",
            name=op.f("analyticsevent_event_type_check"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.user_id"],
            name=op.f("analyticsevent_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("analyticsevent_pkey")),
    )
    op.create_index(
        op.f("index_analytic_usertype"),
        "analyticsevent",
        ["user_id", "event_type"],
        unique=False,
    )
    op.create_table(
        "notification",
        sa.Column("notification_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "sent_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "char_length(message) > 0", name=op.f("notification_message_check")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.user_id"],
            name=op.f("notification_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("notification_id", name=op.f("notification_pkey")),
    )
    op.create_index(
        op.f("index_notifi_user"), "notification", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
